# -*- coding: utf-8 -*-
"""Data-cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_CRCt4Kfwf95TLZgZxF6CDBOVb-z4-H
"""

import pandas as pd

df=pd.read_csv("/content/sample_data/Weather forecast - Sheet 1 - weather_dataset.csv")

df.head(10)

df.dtypes

df.isna().sum()

df[df.duplicated()]

df[df.duplicated('Date')]